setup: &setup
  adapter: postgresql
  host: localhost
  username: postgres
  password:
  encoding: unicode
  min_messages: WARNING

development:
  adapter: postgresql
  host: localhost
  username: syntaxys
  password: 35748199q
  database: {{ name }}_dev

production:
  <<: *setup
  database: {{ name }}_production

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
